import { Obsession } from './types';

export const skills: string[] = [
  'Expert Climber',
  'Lockpicking',
  'Persuasive Liar',
  'Master of Disguise',
  'Incredible Strength',
  'Pyrotechnics',
  'Driving Anything',
  'Animal Whisperer',
  'Weapons Expert',
  'Parkour',
  'Expert Hacker',
  'Mind Reader',
  'Ventriloquism',
  'Stealth Master',
  'Knife Throwing',
  'Speed Runner',
  'Lockjaw (Biting Power)',
  'Hypnotism',
  'Musical Prodigy',
  'Escape Artist',
];

export const obsessions: Obsession[] = [
  { description: 'Collect every shiny object John sees', rank: 1 },
  { description: 'Eat any food in sight', rank: 1 },
  { description: 'Tell everyone John meets his favorite joke', rank: 1 },
  { description: 'Dance in any open space', rank: 1 },
  { description: 'Sing loudly whenever he hears music', rank: 1 },
  { description: 'Pet every dog John encounters', rank: 1 },
  { description: 'High-five strangers on the street', rank: 1 },
  { description: 'Convince people he is a famous celebrity', rank: 1 },
  { description: 'Climb the nearest tree or object', rank: 1 },
  { description: 'Try on every hat he sees', rank: 1 },
  { description: 'Steal any small item he can get his hands on', rank: 2 },
  { description: 'Start fires with random objects', rank: 2 },
  { description: 'Hug everyone wearing blue', rank: 2 },
  { description: 'Break into random cars and pretend to drive', rank: 2 },
  { description: 'Convince others he is an undercover agent', rank: 2 },
  { description: 'Swim in fountains or any large body of water', rank: 2 },
  { description: 'Give passionate speeches about conspiracies', rank: 2 },
  { description: 'Convince a stranger to give him their shoes', rank: 3 },
];
