import { Obsession } from './types';

export const skills: string[] = [
  'Climbing',
  'Lockpicking',
  'Strength',
  'Pyrotechnics',
  'Driving',
  'Hacking',
  'Stealth',
  'Knife Throwing',
  'Running',
  'Biting',
  'Music',
  'Escape Arts',
  'Falconry',
  'Juggling',
  'Whistling',
  'Interpretive Dance',
  'Couponing',
  'Miming',
  'Animal Impressions',
  'Twerking',
  'Balloon Animal Making',
  'Hula Hooping',
  'Stand-Up Comedy',
  'Spelling',
  'Cooking',
  'Conspiracy Theories',
  'Celebrity Impersonation',
  'Eating',
  'Carving',
  'Parkour',
  'Fortune Telling',
  'Ventriloquism',
  'Mustache Styling',
  'Sarcasm',
  'Unicycle Riding'
];

export const obsessions: Obsession[] = [
  { description: 'Beat up a clergyman', rank: 2 },
  { description: 'Eat a baked potato', rank: 1 },
  { description: 'Marry a goat', rank: 3 },
  { description: 'Steal a wedding ring', rank: 2 },
  { description: 'Perform in a concert', rank: 3 },
  { description: 'Start a conga line', rank: 2 },
  { description: 'Trade a shoe with a stranger', rank: 1 },
  { description: 'Convince someone John is royalty', rank: 2 },
  { description: 'Ride a bicycle indoors', rank: 2 },
  { description: 'Get a person’s phone number', rank: 2 },
  { description: 'Buy a pack of raisins', rank: 1 },
  { description: 'Eat a cowboy hat', rank: 2 },
  { description: 'Take a selfie on a stranger’s phone', rank: 1 },
  { description: 'Give someone a piggyback ride', rank: 2 },
  { description: 'Embarrass a politician', rank: 3 },
  { description: 'Start a cult', rank: 3 },
  { description: 'Finish a jar of mayo', rank: 1 },
  { description: 'Be in a shipwreck', rank: 3 },
];
